trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Checkout the code from your repository
- checkout: self
  persistCredentials: true

# Restore dependencies
- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
  displayName: 'Restore NuGet Packages'

# Build the application
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Application'

# Execute deploy.ps1 script
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'deployment.ps1'
    pwsh: true
  displayName: 'Deploy to Azure'